# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa0ba893f1284a59a23d5086d062a3afb2077342bb7706a66894f0b8d8eebb46bb2eede7b45fe7cd6d9142d9528ba1e7dbca65feb7ec22a07ca5d0e5f9876cb

test:
  secret_key_base: a62ffcd08eed3f5cbefdaaee2c3e99a4fbd890ac146497e37a885a4eb2b20286062e681b67d2a0d832a68b8cad4fd7f5739f06e76c03a01d1584d717691008d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
